# Browser Configuration
browser=chrome
headless=false
implicit.wait=10
explicit.wait=20
page.load.timeout=60

# Application URLs
base.url=https://alumni-portal-hazel-tau.vercel.app
login.url=https://alumni-portal-hazel-tau.vercel.app/login
# Admin Credentials (MIT Admin)
admin.username=admin@mit.edu
admin.password=password123
# Super Admin Credentials
superadmin.username=superadmin@alumni.connect
superadmin.password=password123

# Screenshot Configuration
screenshot.on.failure=true
screenshot.path=test-output/screenshots/

# Report Configuration
report.path=test-output/reports/
report.name=Automation_Report

# Retry Configuration
retry.count=0

